---
- name: "Dowload the puppetlabs-release-pc1 deb package"
  get_url:
      url: "https://apt.puppetlabs.com/puppet6-release-{{ ansible_distribution_release }}.deb"
      dest: "/tmp/puppet6-release-{{ ansible_distribution_release }}.deb"

- name: "Install the puppet repos"
  command: "dpkg -i puppet6-release-{{ ansible_distribution_release }}.deb"
  args:
      chdir: /tmp/

- name: "Install puppet-agent"
  apt:
      update_cache: yes
      name: puppet-agent
      state: present

- name: "Set puppet-agent configuration"
  template:
      src: puppet.conf.j2
      dest: /etc/puppetlabs/puppet/puppet.conf

- name: "update hosts file"
  lineinfile:
     dest: /etc/hosts
     line: "{{  puppet_server_ip }} {{  puppet_server_name }}"

- name: "Enable and restart puppet service"
  service:
      name: puppet
      enabled: yes
      state: started
