---
- name: "Dowload the puppetlabs-release-pc1 deb package"
  get_url:
      url: https://apt.puppetlabs.com/puppetlabs-release-pc1-jessie.deb
      dest: /tmp/puppetlabs-release-pc1-jessie.deb

- name: "Install the puppet repos"
  command: dpkg -i puppetlabs-release-pc1-jessie.deb
  args:
      chdir: /tmp/

- name: "Install puppetserver"
  apt:
      update_cache: yes
      name: puppetserver
      state: present

- name: "Set default jvm settings"
  template: 
      src: puppetserver.default.j2
      dest: /etc/default/puppetserver

- name: "Set puppetserver configuration"
  template:
      src: puppet.conf.j2
      dest: /etc/puppetlabs/puppet/puppet.conf

- name: "Enable and restart puppet service"
  service:
      name: puppetserver
      enabled: yes
      state: started
